import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

const Box = () => {
  const repeat = Array(12);
  return (
      [...repeat].map((item, idx) => {
        return (<div className={styles.card} key={idx}>Box</div>)
      })
  )
}

const GridSize = ({gridSize, setGridSet}) => {
  const gridArr = [2, 3, 4, 5, 6]
  return (
      <div className={styles.gridSizes}>
        <h2>Column Width</h2>
        {gridArr.map((elem, idx) => {
          return <GridSizeBox key={idx} elemID={elem} setGridSet={setGridSet}/>
        })}
      </div>
  )
}

const GridSizeBox = ({elemID, setGridSet}) => {
  const handleClick = (e) => {
    const id = e.target.attributes.for.nodeValue
    setGridSet(`${id}`)
  }
  return (
    <>
      <input type="radio" id={`grid-${elemID}`} name='gridSizes'/>
      <label className={styles.card} htmlFor={`grid-${elemID}`} onClick={handleClick}>{elemID}</label>
    </>
  )
}



export default function Home() {
  const [gridSizeColumn, setGridSet] = useState('grid-6')

  return (
    <div className={styles.container}>
      <Head>
        <title>CSS Grid Layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div>
            <p className={styles.title}>CSS Grid Layout</p>
            <p className={styles.description}>Click on Number to change the number of Columns</p>
          </div>
        <div className={`${styles.grid} ${styles[`${gridSizeColumn}`]}`}>
          <GridSize gridSize={gridSizeColumn} setGridSet={setGridSet} />
          <Box />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
